platform :ios, '14.0'

flutter_root = ENV['FLUTTER_ROOT'] || '..'
require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))

install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      # Сбрасываем и переопределяем флаги компилятора для нативного C++ кода (gRPC)
      config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-invalid-command-line-argument'
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-invalid-command-line-argument'

      # Отключаем генерацию дебаг-символов, которая и пытается заюзать флаг -G
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
    end
  end
end