platform :ios, '13.0'

# Изменили строку: теперь подтягиваем официальный встроенный скрипт Flutter
require File.expand_path(File.join('..', '..', 'flutter', 'ephemeral', '.ios', 'Flutter', 'podhelper.rb'), __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_managed_attributes(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end