platform :ios, '13.0'

flutter_root = ENV['FLUTTER_ROOT'] || '..'
require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))

install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # ФИКС: Вырезаем легаси-флаг -G из флагов компилятора для каждого пода
      if config.build_settings['OTHER_CFLAGS']
        config.build_settings['OTHER_CFLAGS'].delete('-G')
      end
      if config.build_settings['OTHER_CPLUSPLUSFLAGS']
        config.build_settings['OTHER_CPLUSPLUSFLAGS'].delete('-G')
      end
    end
  end
end