name: Build_iOS_Standard
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Auto-Generate and Build
        run: |
          # 1. Чистим всё старое, что могло сломаться
          flutter clean
          flutter pub get
          rm -rf ios
          
          # 2. Позволяем Flutter создать ПРАВИЛЬНУЮ папку ios для текущей версии
          flutter create . --platforms=ios
          
          # 3. Запускаем сборку. Flutter сам вызовет pod install и настроит всё как надо.
          # Мы просто добавим флаг, чтобы не требовать подпись.
          flutter build ios --release --no-codesign
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_file
          path: build/ios/iphoneos/*.app
