name: Build_IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Hard Reset iOS and Build
        run: |
          # 1. Очистка кеша
          flutter pub get
          
          # 2. Полное пересоздание платформы iOS (правит все конфиги)
          rm -rf ios
          flutter create . --platforms=ios
          
          # 3. Принудительная версия 13.0 везде
          find . -type f -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' {} +
          
          # 4. Установка подов через сам Flutter (он знает, как их ставить правильно)
          flutter build ios --release --no-codesign --pub
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: my_app_ipa
          path: build/ios/iphoneos/*.app
